apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strimzi-vs-bitnami

helmCharts:
  - repo: https://charts.bitnami.com/bitnami
    name: kafka
    namespace: strimzi-vs-bitnami
    releaseName: kafka
    valuesFile: values.yaml
    version: 20.0.2
