apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argocd-namespace.yaml
  - base/argocd-ingress.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
  - base/kustomized-helm-configmap.yaml

patches:
  - path: patches/kustomized-helm-sidecar.yaml
  - path: patches/anonymous-access.yaml
