apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/kind/deploy.yaml
  - base/tcp-services-configmap.yaml

patches:
  - path: patches/enable-ssl-passthrough.yaml
  - path: patches/add-ports-to-service.yaml
