apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: strimzi-vs-bitnami

helmCharts:
  - repo: https://lsst-sqre.github.io/charts/
    name: kafdrop
    releaseName: kafdrop
    valuesFile: values.yaml
    version: 0.1.3
